### ISSUE TITLE
Fix dependency `future`

### ISSUE THREAD

**Issue by szonszein** [naoki-egami/DIDdesign#34]
Running: did_check(...,
option = list(..., parallel = TRUE, ...))

Getting: Error: 'multiprocess' is not an exported object from 'namespace:future'

Installed `future` version 1.29.0. That fixes the error.

So, either fix package dependency to `future` version 1.29.0. or change function `multiprocess` to new version in 1.33.0.

**Comment by naoki-egami** [comment]
Thank you for the issue. We will fix this asap.

**Comment by szonszein** [comment]
Thank you!
Probably related to parallel setup, another issue is with `did_check_std` when using more than three lags. See below my code and the Error message.

> set.seed(1234)
> check <- did_check(
+   formula = y ~ treatment + post_treat,
+   data    = data,
+   id_time = "time",
+   is_panel = FALSE,
+   option  = list(n_boot = 2000, parallel = TRUE, id_cluster="id", lag = 1:6)
+ )
Error in est_boot_std[, i] : subscript out of bounds
Calls: did_check ... did_check_std -> data.frame -> sd -> var -> is.data.frame
Execution halted
